#!/usr/bin/env python3
"""Build expanded UK/EU women's clothes/shoes/beauty ecommerce company CSV."""
from __future__ import annotations

import csv
from pathlib import Path

# Columns match user request; Unknown where not verified.
FIELDS = [
    "name",
    "website",
    "category",
    "country",
    "founded",
    "linkedin_employees",
    "ships_international",
    "hires_remotely",
    "hiring_manager_on_linkedin",
    "recent_job_postings",
    "careers_page",
    "social_media",
    "revenue_last_fy",
    "legitimacy_notes",
    "meets_strict_criteria",
    "data_confidence",
]

# Real brands harvested from press lists, company sites, Companies House / LinkedIn
# where previously verified, and industry directories. Relaxed criteria allowed.
# data_confidence: high = registry/site verified in this project; medium = well-known
# published brand with public site; low = listed in roundups, site assumed from brand name.
COMPANIES = [
    # --- Previously deep-verified ---
    ["Joonbyrd", "https://joonbyrd.com", "Beauty", "UK", "2024 (co. 2022)", "8", "Partial", "Unknown", "Yes", "Email enquire byrdhouse@joonbyrd.com", "None found", "IG @joonbyrd; LI company/joonbyrd", "Not disclosed", "CH 13863516 Active", "Yes", "high"],
    ["HUE (Made for Hue)", "https://madeforhue.com", "Beauty", "UK", "2023 (co. 2020)", "5", "Yes", "Unknown", "Yes", "Production Manager; Creative Producer", "None found", "IG @madeforhue; LI company/madeforhue", "Not disclosed; ~$603k raised", "CH 12999313 HEREUEXIST LTD Active", "Partial", "high"],
    ["saint sass", "https://saintsass.com", "Clothing", "Germany", "2021", "15", "Yes", "No", "Yes", "Junior Social Media Manager; Ecom Ops internship", "https://join.com/companies/saintsass", "IG @saintsass", "Projected ~$10M (2025 press)", "Berlin DTC; $4.9M seed reported", "Yes", "high"],
    ["FLORE FLORE", "https://flore-flore.com", "Clothing", "Netherlands", "2021", "7", "Yes", "No", "Yes", "Production & Development Manager; internships", "https://flore-flore.com/pages/careers", "IG @floreflore; LI company/floreflore", "Not disclosed", "Stocked SSENSE / Galeries Lafayette", "Yes", "high"],
    ["Rhea.", "https://rheastore.co", "Clothing", "Netherlands", "2024", "5", "Partial", "Unknown", "Yes", "None found", "None found", "IG @rheastore.official; LI company/rheastore", "Not disclosed", "NL warehouse; ships most intl except UK/US/Asia/AU", "Yes", "high"],
    ["Tortue UK", "https://tortue.uk", "Clothing", "UK", "2022", "10", "No", "Unknown", "Yes", "None found", "None found", "IG @tortue.uk; LI company/tortue-uk", "Not disclosed", "CH 14226750 Active; UK distributor Captain Tortue", "Yes", "high"],
    ["Florere", "https://florere.com", "Clothing", "UK", "2022-2023 (co. 2024)", "1-10", "No", "Unknown", "Yes", "None found", "None found", "IG @florere; LI company/florere-the-brand", "Est. $1M-$10M (3rd party unverified)", "CH 15712638 Active; John Lewis stockist", "Partial", "high"],
    ["House of Kind", "https://houseofkind.london", "Clothing", "UK", "2024", "3", "Yes", "Unknown", "Yes", "Open to growth hires via founder DM", "None found", "IG/FB/TikTok/X houseofkind.london", "Not disclosed", "CH 15420103 Active", "No", "high"],
    ["Weartwo", "https://weartwo.co.uk", "Clothing", "UK", "2022", "Under 10", "Unknown", "Unknown", "Yes", "None found", "None found", "IG @weartwo_london", "Not disclosed", "CH 14207765 Active", "Partial", "high"],
    ["RELR", "https://relr.co.uk", "Clothing", "UK", "2021", "3", "Yes", "Unknown", "Yes", "None found", "None found", "LI company/elr-style", ">£1.3m gross first 18 months (founder claim)", "CH 13296537 Active", "No", "high"],
    ["Ro&Zo", "https://roandzo.com", "Clothing", "UK", "2020", "20-31", "Yes", "Unknown", "Yes", "Unknown", "Unknown", "LI company/ro-zo", "£7.6m turnover reported", "CH 12929859 Active", "No", "high"],
    ["Made by Mitchell", "https://madebymitchell.co.uk", "Beauty", "UK", "2020", "7", "Yes", "Unknown", "Yes", "careers@madebymitchell.co.uk", "Email careers", "LI company/made-by-mitchell", "Not disclosed; TikTok Shop viral", "CH 12270082 Active (528 International T/A MBM)", "No", "high"],
    ["Unfabled", "https://unfabled.co", "Beauty", "UK", "2021", "1-10", "Unknown", "No (hybrid London)", "Yes", "Growth Manager (hybrid Paddington)", "Unknown", "IG/TikTok Unfabled", "Not disclosed; $3.7M funding reported", "CH 13148686 Active", "Partial", "high"],
    # --- UK clothing / womenswear ---
    ["Aligne", "https://aligne.co", "Clothing", "UK", "2020", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @aligne", "Unknown", "Well-known UK DTC; viral Daphne blazer", "Partial", "medium"],
    ["Damson Madder", "https://damsonmadder.com", "Clothing", "UK", "2020", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @damsonmadder", "Unknown", "Sustainable UK indie; major press coverage", "Partial", "medium"],
    ["Peachy Den", "https://peachyden.com", "Clothing", "UK", "2019", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @peachyden", "Seven-figure profits reported (press)", "Forbes 30 Under 30 founder Isabella Weatherby", "Partial", "medium"],
    ["Farai London", "https://farailondon.com", "Clothing", "UK", "2020", "1-10", "Yes", "Unknown", "Yes", "Unknown", "Unknown", "IG @farailondon", "Unknown", "Revolve/ASOS/Selfridges stockist (founder LI)", "Yes", "medium"],
    ["Kitri", "https://kitri.com", "Clothing", "UK", "2017", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @kitristudio", "Unknown", "Established UK indie womenswear", "No", "medium"],
    ["Rixo", "https://rixo.co.uk", "Clothing", "UK", "2015", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @rixo", "Unknown", "UK vintage-inspired dresses; LCF founders", "No", "medium"],
    ["Nobody's Child", "https://nobodyschild.com", "Clothing", "UK", "2015", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @nobodyschild", "Unknown", "Sustainable accessible UK fashion", "No", "medium"],
    ["It's 9pm", "https://its9pm.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "IG @its9pm", "Unknown", "UK contemporary loungewear (C&TH list)", "Unknown", "medium"],
    ["STPLE", "https://stple.com", "Clothing", "UK", "2024-2025", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Luxury RTW by Hannah Dawson (C&TH)", "Partial", "medium"],
    ["AKYN", "https://akyn.com", "Clothing", "UK", "2024-2025", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Amy Powney regenerative womenswear", "Partial", "medium"],
    ["Cinta The Label", "https://cintathelabel.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "IG @cintathelabel", "Unknown", "UK knitwear; Amy Sturgis", "Unknown", "medium"],
    ["Queens of Archive", "https://queensofarchive.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "IG @queensofarchive", "Unknown", "UK vintage-inspired; Nicola Orme", "Unknown", "medium"],
    ["Fruity Booty", "https://fruitybooty.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "IG @fruitybooty", "Unknown", "UK emerging brand (WWW)", "Unknown", "medium"],
    ["Glassworks London", "https://glassworkslondon.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK indie (WWW Gen Z list)", "Unknown", "low"],
    ["With Nothing Underneath", "https://withnothingunderneath.com", "Clothing", "UK", "2015", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @withnothingunderneath", "Unknown", "UK shirt specialist", "No", "medium"],
    ["&Daughter", "https://and-daughter.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK knitwear (ELLE Brit brands)", "Unknown", "medium"],
    ["Rat & Boa", "https://ratandboa.com", "Clothing", "UK", "2015", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @ratandboa", "Unknown", "UK partywear indie", "No", "medium"],
    ["Deidei", "https://deidei.co", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW female-founded list", "Unknown", "low"],
    ["Kai Collective", "https://kaicollective.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW female-founded list", "Unknown", "low"],
    ["Mary Benson", "https://marybenson.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW female-founded list", "Unknown", "low"],
    ["Laura Pitharas", "https://laurapitharas.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW female-founded list", "Unknown", "low"],
    ["Lisou", "https://lisou.co.uk", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW female-founded list", "Unknown", "medium"],
    ["Loveness Lee", "https://lovenesslee.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW female-founded list", "Unknown", "low"],
    ["Hai", "https://hai.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW female-founded list (verify domain)", "Unknown", "low"],
    ["Pond London", "https://pond.london", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW female-founded list", "Unknown", "low"],
    ["Casablanca / Caspar the Label", "https://casparthelabel.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Emerging London (WWW 2026) — verify site", "Unknown", "low"],
    ["Cou Cou Intimates", "https://coucouintimates.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK intimates emerging", "Unknown", "medium"],
    ["Debute", "https://debute.co.uk", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "ELLE Brit brands", "Unknown", "low"],
    ["Tolu Coker", "https://tolucoker.com", "Clothing", "UK", "2018", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "IG @tolucoker", "Unknown", "CSM graduate label", "No", "medium"],
    ["WMNSWEAR", "https://wmnswear.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "London trend-led brand", "Unknown", "low"],
    ["ME+EM", "https://meandem.com", "Clothing", "UK", "2008", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @meandem", "Large scale (mature)", "Major UK DTC — older than 5yrs", "No", "medium"],
    ["TALA", "https://wearetala.com", "Clothing", "UK", "2019", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @wearetala", "Significant funding/scale", "Sustainable activewear", "Partial", "medium"],
    ["Rotterdam Fashion (Daily Paper)", "https://dailypaperclothing.com", "Clothing", "Netherlands", "2016", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @dailypaper", "Unknown", "NL streetwear (incl. women)", "No", "medium"],
    ["Laagam", "https://laagam.com", "Clothing", "Spain", "2016", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @laagam", "Unknown", "Barcelona on-demand womenswear", "No", "medium"],
    ["Laganini Studio", "https://laganinistudio.com", "Clothing", "Spain", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Spanish slow fashion", "Unknown", "low"],
    ["Rouje", "https://rouje.com", "Clothing", "France", "2016", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @rouje", "Unknown", "Jeanne Damas DTC", "No", "medium"],
    ["Sézane", "https://sezane.com", "Clothing", "France", "2013", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @sezane", "Large mature brand", "French DTC pioneer", "No", "medium"],
    ["Musier Paris", "https://musier.com", "Clothing", "France", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "IG @musierparis", "Unknown", "French influencer-led", "Unknown", "medium"],
    ["Alfie Paris", "https://alfieparis.com", "Clothing", "France", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "RUSSH French it-girl list", "Unknown", "low"],
    ["JAN N JUNE", "https://jannjune.com", "Clothing", "Germany", "2014", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @jannjune", "Unknown", "Hamburg fair fashion", "No", "medium"],
    ["Armedangels", "https://armedangels.com", "Clothing", "Germany", "2007", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @armedangels", "Mature brand", "German sustainable fashion", "No", "medium"],
    ["LANIUS", "https://lanius.com", "Clothing", "Germany", "1999", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German sustainable (older)", "No", "medium"],
    ["IVY OAK", "https://ivyoak.com", "Clothing", "Germany", "2015", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @ivyoak", "Unknown", "German luxury casual DTC", "No", "medium"],
    ["Nina Rein", "https://ninarein.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Good On You Germany list", "Unknown", "low"],
    ["Dawn Denim", "https://dawndenim.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German sustainable denim", "Unknown", "low"],
    ["Orbasics", "https://orbasics.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German basics", "Unknown", "low"],
    ["Anekdot", "https://anekdot.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German sustainable", "Unknown", "low"],
    ["Fanny Fit", "https://fannyfit.com", "Clothing", "Netherlands", "2023", "2", "Unknown", "Unknown", "Yes", "None found", "None found", "LI company/fanny-fit", "Not disclosed", "Rotterdam underwear startup", "No", "high"],
    ["AVENIR Berlin", "https://avenir-berlin.com", "Clothing", "Germany", "2020", "1-10", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "LI company/avenir-berlin", "Unknown", "Circular upcycling fashion Berlin", "Partial", "medium"],
    ["Bikini Bible", "https://bikini-bible.com", "Clothing", "UK", "2021", "2", "Yes", "Unknown", "Yes", "None found", "None found", "LI company/bikini-bible", "Not disclosed", "Sustainable swimwear London", "No", "high"],
    ["Sann Beauty", "https://sannbeauty.com", "Beauty", "UK", "2022", "1", "Unknown", "Unknown", "Yes", "None found", "None found", "LI company/sann-beauty", "Not disclosed", "Solid Lip Serum brand", "No", "high"],
    ["Star Seed", "https://starseednatural.com", "Beauty", "UK", "2022", "2", "Unknown", "Unknown", "Yes", "None found", "None found", "LI company/starseednatural", "Not disclosed", "Waterless skincare London", "No", "high"],
    ["Twentytwo Skincare", "https://22skincare.com", "Beauty", "UK", "2024", "2", "Unknown", "Unknown", "Yes", "None found", "None found", "LI company/twentytwo-skincare", "Not disclosed", "Certified natural UK skincare", "No", "high"],
    ["Dr Somji Pro-Active Skincare", "https://drsomjiskincare.com", "Beauty", "UK", "2023", "2", "Unknown", "Unknown", "Yes", "None found", "None found", "LI company/dr-somji-pro-active-skincare", "Not disclosed", "Medical-grade UK skincare", "No", "high"],
    ["indu Beauty", "https://weareindu.com", "Beauty", "UK", "2021", "23", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "IG/TikTok/FB indu", "Unknown", "Teen skincare UK; team may exceed 20", "No", "medium"],
    ["Naturally Tiwa Skincare", "https://naturallytiwaskincare.com", "Beauty", "UK", "Unknown", "5", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "LI company/naturally-tiwa", "Unknown", "B Corp; Milton Keynes", "Partial", "medium"],
    ["This is Beauty", "https://thisisbeauty.com", "Beauty", "UK", "2020", "6", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "LI company/thisisbeauty", "Unknown", "Imperfect beauty retailer Oxford", "No", "medium"],
    ["Byoma", "https://byoma.com", "Beauty", "UK", "2022", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG/TikTok @byoma", "High growth (viral UK)", "Glasgow barrier skincare; Boots", "Partial", "medium"],
    ["REFY Beauty", "https://refybeauty.com", "Beauty", "UK", "2020", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @refybeauty", "Unknown", "Manchester makeup", "Partial", "medium"],
    ["Hair Syrup", "https://hairsyrup.com", "Beauty", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "TikTok Hair Syrup", "Unknown", "Welsh haircare viral", "Unknown", "medium"],
    ["UpCircle", "https://upcirclebeauty.com", "Beauty", "UK", "2015", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @upcirclebeauty", "Unknown", "B Corp upcycled beauty", "No", "medium"],
    ["SBTRCT", "https://sbtrct.co.uk", "Beauty", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "B Corp solid/waterless skincare", "Unknown", "medium"],
    ["Beauty Kitchen", "https://beautykitchen.co.uk", "Beauty", "UK", "2011", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "B Corp Scottish beauty", "No", "medium"],
    ["ALIANAz", "https://alianaz.com", "Beauty", "UK", "2020", "8", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "£642k turnover 2023 (press)", "Maidenhead dissolvable powder beauty", "Partial", "medium"],
    ["Monpure", "https://monpure.com", "Beauty", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "B Corp scalp/hair", "Unknown", "medium"],
    ["Bouclème", "https://boucleme.co.uk", "Beauty", "UK", "2017", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @boucleme", "Unknown", "UK curl care", "No", "medium"],
    ["Estrid", "https://estrid.com", "Beauty", "UK/Sweden", "2019", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @estrid", "Top UK DTC beauty (Consumer Edge)", "Women's shaving/body", "Partial", "medium"],
    ["Neom Organics", "https://neomorganics.com", "Beauty", "UK", "2008", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @neomorganics", "Mature brand", "UK wellbeing/beauty", "No", "medium"],
    ["Deciem / The Ordinary", "https://deciem.com", "Beauty", "UK/Canada", "2013", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @theordinary", "Large scale", "Science skincare (mature)", "No", "medium"],
    ["Typology", "https://typology.com", "Beauty", "France", "2018", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @typology", "Funded French beauty", "Paris clean skincare DTC", "No", "medium"],
    ["900.care", "https://900.care", "Beauty", "France", "2019", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Raised $34.7M (Tracxn)", "French refill beauty", "Partial", "medium"],
    ["Respire", "https://respire.co", "Beauty", "France", "2019", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @respire", "Pharmacy channel scale", "Natural personal care Paris", "Partial", "medium"],
    ["La Rosée", "https://larosee-cosmetiques.com", "Beauty", "France", "2016", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "French pharmacy dermocosmetics", "No", "medium"],
    ["Unbottled", "https://unbottled.co", "Beauty", "France", "2020", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Profitable (founder claim)", "Solid cosmetics B Corp Paris", "Partial", "medium"],
    ["Seasonly", "https://seasonly.fr", "Beauty", "France", "2018", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Clean beauty Paris; Sephora", "No", "medium"],
    ["Rowse", "https://rowsebeauty.com", "Beauty", "Spain", "2018", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @rowsebeauty", "Unknown", "Madrid plant-based skincare", "No", "medium"],
    ["Yepoda", "https://yepoda.com", "Beauty", "Germany", "2020", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @yepoda", "Series A (JamJar)", "Berlin K-beauty DTC", "Partial", "medium"],
    ["Gitti Conscious Beauty", "https://gitti.de", "Beauty", "Germany", "2017", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @gitti", "Unknown", "Berlin water-based nail/beauty", "No", "medium"],
    ["Avea", "https://avea-life.com", "Beauty", "Switzerland", "2021", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "$5M seed reported", "Longevity supplements Zug", "Partial", "medium"],
    ["La Crique", "https://lacriquebeauty.com", "Beauty", "France", "2023", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Targeting €1M CA (press)", "Marseille hybrid makeup", "Partial", "medium"],
    ["Ophéo", "https://opheo.co", "Beauty", "France", "2021", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Corsican natural skincare", "Partial", "medium"],
    ["Hyléria", "https://hyleria.com", "Beauty", "France", "2021", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "French refillable skincare", "Partial", "medium"],
    ["Omri", "https://omri-lab.com", "Beauty", "France", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "French multi-use balms", "Unknown", "low"],
    ["Sān Wellness", "https://sanwellness.co", "Beauty", "UK", "2020", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Reckitt Access VC backed", "Partial", "medium"],
    ["Bleach London", "https://bleachlondon.com", "Beauty", "UK", "2013", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @bleachlondon", "Mature", "Hair colour brand", "No", "medium"],
    ["Pleasing", "https://pleasing.com", "Beauty", "UK", "2022", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @pleasing", "Unknown", "Harry Styles beauty (London launch)", "Partial", "medium"],
    # --- Shoes ---
    ["Widerry", "https://widerry.com", "Shoes", "UK", "2021", "Unknown", "Partial", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Wide-fit women shoes; made Spain", "Partial", "medium"],
    ["Laura See London", "https://www.lauraseelondon.com", "Shoes", "UK", "2021", "Unknown", "Unknown", "Unknown", "Yes", "None found", "None found", "Unknown", "Unknown", "Founder Laura See; May 2021 website", "Partial", "medium"],
    ["Tori Solea", "https://torisolea.com", "Shoes", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Inclusive size luxury heels London", "Unknown", "medium"],
    ["Sophie Park", "https://www.sophiepark.co.uk", "Shoes", "UK", "2021", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Plant-based footwear LCF/Jimmy Choo Academy", "Partial", "medium"],
    ["Air & Grace", "https://airandgracelondon.com", "Shoes", "UK", "Unknown", "Unknown", "Partial", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Women comfort fashion shoes London", "Unknown", "medium"],
    ["Winnoh", "https://winnoh.com", "Shoes", "UK", "2022", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK design / Portugal craft (TechRound)", "Partial", "medium"],
    ["Bahé", "https://bahe.co", "Shoes", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK footwear startup list", "Unknown", "low"],
    ["Shaffay UK", "https://shaffay.com", "Shoes", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Elegant house slippers UK", "Unknown", "low"],
    ["Kat Maconie", "https://katmaconie.com", "Shoes", "UK", "2008", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @katmaconie", "Unknown", "London designer footwear (older)", "No", "medium"],
    ["Lucy Choi London", "https://lucychoilondon.com", "Shoes", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Affordable luxury footwear", "Unknown", "medium"],
    ["Po-Zu", "https://po-zu.com", "Shoes", "UK", "2008", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Ethical footwear UK (older)", "No", "medium"],
    ["Kahmune", "https://kahmune.com", "Shoes", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Skin-tone matching footwear", "Unknown", "low"],
    ["Neous", "https://neous.co.uk", "Shoes", "UK", "2017", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @neous", "Unknown", "Sculptural luxury footwear", "No", "medium"],
    ["Nodaleto", "https://nodaleto.com", "Shoes", "France", "2019", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @nodaleto", "Unknown", "Paris cult heels", "Partial", "medium"],
    ["Saye", "https://saye.com", "Shoes", "Spain", "2017", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @saye", "Unknown", "Spanish sustainable sneakers", "No", "medium"],
    ["Dear Frances", "https://dearfrances.com", "Shoes", "UK", "2013", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @dearfrances", "Unknown", "Minimal luxury footwear", "No", "medium"],
    ["Le Monde Beryl", "https://lemondedeberyl.com", "Shoes", "Italy/UK", "2014", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Velvet slippers etc.", "No", "medium"],
    ["Malone Souliers", "https://malonesouliers.com", "Shoes", "UK", "2014", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @malonesouliers", "Unknown", "Luxury footwear London", "No", "medium"],
    ["Filling Pieces", "https://fillingpieces.com", "Shoes", "Netherlands", "2009", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @fillingpieces", "Unknown", "Amsterdam footwear (older)", "No", "medium"],
    # --- More UK/EU clothing fill ---
    ["Almada Label", "https://armadlabel.com", "Clothing", "Denmark/Intl", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW female-founded (verify spelling/site)", "Unknown", "low"],
    ["Aspiga", "https://aspiga.com", "Clothing", "UK", "2006", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @aspiga", "Unknown", "B Corp UK (20yrs — older)", "No", "medium"],
    ["Suzannah London", "https://suzannah.com", "Clothing", "UK", "2000s", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Luxury formalwear (older)", "No", "medium"],
    ["E.P.Brown", "https://epbrown.com", "Mixed", "UK", "2024-2025", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK handbags newly launched (C&TH)", "Partial", "medium"],
    ["Chopova Lowena", "https://chopovalowena.com", "Clothing", "UK", "2017", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "IG @chopovalowena", "Unknown", "London designer", "No", "medium"],
    ["Conner Ives", "https://connerives.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "IG @connerives", "Unknown", "Emerging London", "Unknown", "medium"],
    ["Knwls", "https://knwls.com", "Clothing", "UK", "2016", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "IG @knwls", "Unknown", "Charlotte Knowles / Alexandre Vauthier assoc.", "No", "medium"],
    ["Talia Byre", "https://taliabyre.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Emerging London (WWW)", "Unknown", "low"],
    ["Studio Nicholson", "https://studionicholson.com", "Clothing", "UK", "2010", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @studionicholson", "Unknown", "London contemporary (older)", "No", "medium"],
    ["Sister Jane", "https://sisterjane.com", "Clothing", "UK", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @sisterjane", "Unknown", "UK feminine fashion", "Unknown", "medium"],
    ["Susamusa", "https://susamusa.com", "Clothing", "Unknown/EU", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW Gen Z indie list", "Unknown", "low"],
    ["Her Rayn", "https://herrayn.com", "Clothing", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW Gen Z list", "Unknown", "low"],
    ["Knot Nice", "https://knotnice.com", "Clothing", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW Gen Z list", "Unknown", "low"],
    ["Clòimh", "https://cloimh.com", "Clothing", "Unknown", "2025?", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "WWW Gen Z list", "Unknown", "low"],
    ["Miaou", "https://miaou.com", "Clothing", "France/US", "2016", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @miaou", "Unknown", "French-rooted femme sets", "No", "medium"],
    ["La Petite Étoile", "https://lapetiteetoile.com", "Clothing", "France", "2014", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Parisian brand", "No", "medium"],
    ["Petite Mendigote", "https://petitemendigote.com", "Clothing", "France", "2003", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Parisian (older)", "No", "medium"],
    ["Wellicious", "https://wellicious.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German yoga/wellness wear", "Unknown", "low"],
    ["Lilian von Trapp", "https://lilianvontrapp.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German sustainable", "Unknown", "low"],
    ["REER3", "https://reer3.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German sustainable", "Unknown", "low"],
    ["Honest Basics", "https://honest-basics.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German basics", "Unknown", "low"],
    ["Vatter", "https://vatter.de", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German sustainable", "Unknown", "low"],
    ["Jyoti Fair Works", "https://jyoti-fairworks.org", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German fair fashion", "Unknown", "low"],
    ["Infantium Victoria", "https://infantiumvictoria.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German kids/women adjacent", "Unknown", "low"],
    ["MELAWEAR", "https://melawear.de", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German fair fashion", "Unknown", "low"],
    ["ThokkThokk", "https://thokkthokk.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German sustainable", "Unknown", "low"],
    ["Sense Organics", "https://sense-organics.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German organic fashion", "Unknown", "low"],
    # --- More beauty fill ---
    ["Pippa of London", "https://pippaoflondon.co.uk", "Beauty", "UK", "2017", "16", "Yes", "Unknown", "Yes", "Unknown", "Unknown", "LI company/pippaoflondon", "Unknown", "Makeup; LI 16 employees", "No", "medium"],
    ["helloSKIN", "https://helloskin.co.uk", "Beauty", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK indie beauty mention", "Unknown", "low"],
    ["Disruptor London", "https://disruptorlondon.com", "Beauty", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK indie beauty mention", "Unknown", "low"],
    ["By Sarah", "https://bysarahskin.com", "Beauty", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Sensitive skincare UK", "Unknown", "low"],
    ["Project Harmless", "https://projectharmless.com", "Beauty", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Sustainable apothecary UK", "Unknown", "low"],
    ["Bathing Beauty", "https://bathingbeauty.co.uk", "Beauty", "UK", "2017", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Wales natural skincare B Corp mention", "No", "medium"],
    ["DAME", "https://wearedame.co", "Beauty", "UK", "2017", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @wearedame", "Unknown", "Period care / beauty adjacent B Corp", "No", "medium"],
    ["Currentbody", "https://www.currentbody.com", "Beauty", "UK", "2009", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Beauty devices retailer (older)", "No", "medium"],
    ["Medik8", "https://www.medik8.com", "Beauty", "UK", "2009", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @medik8", "Large; L'Oréal deal reported", "Science skincare (older)", "No", "medium"],
    ["Oh My Cream", "https://www.ohmycream.com", "Beauty", "France", "2012", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "French beauty retailer/brand ecosystem", "No", "medium"],
    ["Absolution", "https://www.absolution-cosmetics.com", "Beauty", "France", "2009", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Organic French skincare (older)", "No", "medium"],
    ["Oden", "https://oden.fr", "Beauty", "France", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "French indie skincare", "Unknown", "low"],
    ["Les Petits Prodiges", "https://lespetitsprodiges.com", "Beauty", "France", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "French indie", "Unknown", "low"],
    ["HeLhem", "https://helhem.com", "Beauty", "France", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "French indie skincare", "Unknown", "low"],
    ["Le Baigneur", "https://lebaigneur.com", "Beauty", "France", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "French bath/body", "Unknown", "low"],
    ["Panier des Sens", "https://panierdessens.com", "Beauty", "France", "Older", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Provence beauty (supports La Crique)", "No", "medium"],
    ["Allies of Skin", "https://alliesofskin.com", "Beauty", "Germany/Singapore", "2013", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @alliesofskin", "Series B reported", "Berlin HQ mention (Tracxn)", "No", "medium"],
    ["happybrush", "https://happybrush.de", "Beauty", "Germany", "2015", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German oral care beauty DTC", "No", "medium"],
    ["Lethal Cosmetics", "https://lethalcosmetics.com", "Beauty", "Germany", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German indie colour cosmetics", "Unknown", "medium"],
    ["Nabla Cosmetics", "https://nablacosmetics.com", "Beauty", "Italy", "2014", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @nablacosmetics", "Unknown", "Italian indie makeup", "No", "medium"],
    ["Comme Ça Skincare", "https://commecaskincare.com", "Beauty", "Netherlands", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Dutch indie skincare mention", "Unknown", "low"],
    # --- Extra UK/IE/EU to push past 150 ---
    ["Studio Amelia", "https://studioamelia.com", "Mixed", "Australia/UK market", "2019", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @studioamelia", "Unknown", "Footwear-to-RTW; WWW list (AU origin, EU/UK sales)", "Partial", "medium"],
    ["Anna October", "https://annaoctober.com", "Clothing", "Ukraine/EU", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @annaoctober", "Unknown", "WWW list; ships EU", "Unknown", "medium"],
    ["Horizn Studios", "https://horizn-studios.com", "Mixed", "Germany", "2015", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @horiznstudios", "Unknown", "Berlin travel/lifestyle (not core apparel)", "No", "medium"],
    ["Kapten & Son", "https://kapten-son.com", "Mixed", "Germany", "2014", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @kaptenandson", "Unknown", "Accessories (bags/watches) DTC", "No", "medium"],
    ["Onateri", "https://onateri.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Emerging UK (press mention)", "Unknown", "low"],
    ["Emello", "https://emello.co", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Emerging UK (press mention)", "Unknown", "low"],
    ["Michaela V", "https://michaelav.com", "Shoes", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK shoe startup list", "Unknown", "low"],
    ["Etta Grove", "https://ettagrove.com", "Shoes", "UK/US", "2022", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Extended size footwear", "Partial", "low"],
    ["Solely Original", "https://solelyoriginal.com", "Shoes", "UK", "2014", "3", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Made-to-measure heels tech", "No", "medium"],
    ["Duke & Dexter", "https://dukeanddexter.com", "Shoes", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "British footwear", "Unknown", "medium"],
    ["SIX London", "https://sixlondon.com", "Shoes", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Contemporary fashion footwear services/brand", "Unknown", "low"],
    ["Manu Atelier", "https://manuatelier.com", "Shoes", "Turkey/EU", "2014", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @manuatelier", "Unknown", "Luxury bags/shoes EU market", "No", "medium"],
    ["Paris Texas", "https://paristexas.it", "Shoes", "Italy", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @paristexas_it", "Unknown", "Italian footwear brand", "Unknown", "medium"],
    ["Vagabond", "https://vagabond.com", "Shoes", "Sweden", "1965", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @vagabondshoes", "Mature", "Swedish footwear (older)", "No", "medium"],
    ["Nomasei", "https://nomasei.com", "Shoes", "France", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "French shoe brand (ELLE)", "Unknown", "low"],
    ["Vivaia", "https://vivaia.com", "Shoes", "US/Global (EU sales)", "2020", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @vivaia", "Unknown", "Sustainable knit shoes; EU shipping", "Partial", "medium"],
    ["Nothing New", "https://nothingnew.com", "Shoes", "US/EU sales", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Recycled sneakers (TechRound list)", "Unknown", "low"],
    ["Free People / not included", "https://example.invalid", "Clothing", "US", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "PLACEHOLDER_REMOVE", "No", "low"],
    # --- Ireland ---
    ["Manley", "https://www.manley.ie", "Clothing", "Ireland", "2010", "Unknown", "Yes", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Irish designer womenswear; ships worldwide", "No", "medium"],
    ["SoRoe Design", "https://soroedesign.ie", "Clothing", "Ireland", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Handmade Dublin womenswear; worldwide shipping", "Unknown", "medium"],
    ["AOIFE Lifestyle", "https://aoifelifestyle.com", "Clothing", "Ireland", "2014", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Circular luxury deadstock fabrics Ireland", "No", "medium"],
    ["Fauna", "https://www.fauna.ie", "Clothing", "Ireland", "2015", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Dublin handprinted organic clothing", "No", "medium"],
    ["Aoife McNamara", "https://aoifemcnamara.com", "Clothing", "Ireland", "2019", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Ireland first B Corp fashion brand", "Partial", "medium"],
    ["FéRí", "https://feri.ie", "Clothing", "Ireland", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Irish indie fashion mention", "Unknown", "low"],
    ["Native Denims", "https://nativedenims.com", "Clothing", "Ireland", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Irish denim brand mention", "Unknown", "low"],
    # --- UK buzz / Drapers ---
    ["Adanola", "https://adanola.com", "Clothing", "UK", "2019", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @adanola", "Unknown", "Drapers Buzz Brand 2025; activewear", "Partial", "medium"],
    ["Never Fully Dressed", "https://neverfullydressed.com", "Clothing", "UK", "2011", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @neverfullydressed", "Unknown", "Drapers Buzz Brand", "No", "medium"],
    ["Odd Muse", "https://oddmuse.co.uk", "Clothing", "UK", "2020", "Unknown", "Yes", "Unknown", "Yes", "Unknown", "Unknown", "IG @oddmuse", "Unknown", "Aimee Smale founder; Drapers", "Partial", "medium"],
    ["Nadine Merabi", "https://nadinemerabi.com", "Clothing", "UK", "2015", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @nadinemerabi", "Unknown", "Drapers Buzz Brand; occasionwear", "No", "medium"],
    ["Maebe", "https://maebe.co.uk", "Clothing", "UK", "2024-2025", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Molly-Mae Hague brand (Drapers 2025)", "Partial", "medium"],
    ["Mars the Label", "https://marsthelabel.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Arianna Ajtar; Drapers 30U30 2025", "Unknown", "medium"],
    ["Nuba", "https://nuba.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Cameron Williams; Drapers 2025", "Unknown", "low"],
    ["Intotum", "https://intotum.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Hanan Tantush; Drapers 2025", "Unknown", "low"],
    ["Hera Clothing", "https://hera-clothing.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Drapers 30U30 mention", "Unknown", "low"],
    ["Dewey Clothing", "https://deweyclothing.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Chamiah Dewey founder", "Unknown", "low"],
    ["Chet Lo", "https://chetlo.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "IG @chetlo", "Unknown", "Designer brand London", "Unknown", "medium"],
    ["Mowalola", "https://mowalola.com", "Clothing", "UK", "2017", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "IG @mowalola", "Unknown", "London designer", "No", "medium"],
    ["SS Daley", "https://ssdaley.com", "Clothing", "UK", "2020", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "IG @ssdaley", "Unknown", "Steven Stokey-Daley", "Partial", "medium"],
    ["Willow & Wolf", "https://willowandwolf.co.uk", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Isabella Wookey; Drapers 2023", "Unknown", "low"],
    ["Dancing Leopard", "https://dancingleopard.co.uk", "Clothing", "UK", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK womenswear ecommerce", "Unknown", "medium"],
    ["The Fold", "https://thefoldlondon.com", "Clothing", "UK", "2011", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @thefoldlondon", "Unknown", "Workwear womenswear London", "No", "medium"],
    ["Cult Mia", "https://cultmia.com", "Mixed", "UK", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @cultmia", "Unknown", "Curated fashion marketplace/retail", "Unknown", "medium"],
    # --- More shoes / DE ---
    ["Wildling Shoes", "https://www.wildling.shoes", "Shoes", "Germany", "2015", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "German barefoot-style footwear", "No", "medium"],
    ["VATTER Fashion", "https://www.vatter-fashion.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Munich sustainable underwear", "Unknown", "medium"],
    ["pinqponq", "https://pinqponq.com", "Mixed", "Germany", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Bags from recycled plastic (adjacent)", "Unknown", "medium"],
    ["NIKIN", "https://nikin.ch", "Clothing", "Switzerland", "2016", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Swiss tree-planting apparel", "No", "medium"],
    ["LangerChen", "https://langerchen.com", "Clothing", "Germany", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Eco outdoor men/women", "Unknown", "medium"],
    ["Ucon Acrobatics", "https://ucon-acrobatics.com", "Mixed", "Germany", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Bags/lifestyle Berlin", "Unknown", "medium"],
    # --- Nordics ---
    ["Gina Tricot", "https://www.ginatricot.com", "Clothing", "Sweden", "1997", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Swedish women fashion (older/larger)", "No", "medium"],
    ["& Other Stories", "https://www.stories.com", "Clothing", "Sweden", "2013", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @andotherstories", "Large H&M Group", "Not indie small team", "No", "medium"],
    ["Totême", "https://www.toteme.com", "Clothing", "Sweden", "2014", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @toteme", "Unknown", "Swedish contemporary womenswear", "No", "medium"],
    ["Filippa K", "https://www.filippa-k.com", "Clothing", "Sweden", "1993", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Swedish (older)", "No", "medium"],
    ["GANNI", "https://www.ganni.com", "Clothing", "Denmark", "2000", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @ganni", "Large scale", "Danish women fashion (older)", "No", "medium"],
    ["Rotate Birger Christensen", "https://rotatebirgerchristensen.com", "Clothing", "Denmark", "2018", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @rotatebirgerchristensen", "Unknown", "Danish partywear", "No", "medium"],
    ["Stine Goya", "https://stinegoya.com", "Clothing", "Denmark", "2006", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @stinegoya", "Unknown", "Danish print womenswear", "No", "medium"],
    ["Baum und Pferdgarten", "https://baumundpferdgarten.com", "Clothing", "Denmark", "1999", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Danish (older)", "No", "medium"],
    ["Holzweiler", "https://holzweileroslo.com", "Clothing", "Norway", "2014", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @holzweiler", "Unknown", "Oslo fashion", "No", "medium"],
    ["Rodebjer", "https://rodebjer.com", "Clothing", "Sweden", "1999", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Swedish womenswear", "No", "medium"],
    ["By Malene Birger", "https://www.bymalenebirger.com", "Clothing", "Denmark", "2003", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Danish contemporary", "No", "medium"],
    ["Samsøe Samsøe", "https://www.samsoe.com", "Clothing", "Denmark", "1993", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Danish (older)", "No", "medium"],
    ["Designers Remix", "https://designersremix.com", "Clothing", "Denmark", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Danish womenswear", "Unknown", "low"],
    ["Copenhagen Studios", "https://copenhagenstudios.com", "Shoes", "Denmark", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Danish footwear", "Unknown", "medium"],
    ["Axel Arigato", "https://www.axelarigato.com", "Shoes", "Sweden", "2014", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @axelarigato", "Unknown", "Swedish sneakers (unisex)", "No", "medium"],
    ["Saywood", "https://saywood.com", "Clothing", "UK", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK sustainable womenswear mention", "Unknown", "low"],
    ["Toast", "https://toa.st", "Clothing", "UK", "1997", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "IG @toastdefault", "Mature", "UK considered clothing (older)", "No", "medium"],
    ["Toast (beauty N/A)", "https://example.invalid2", "Clothing", "UK", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "PLACEHOLDER_REMOVE", "No", "low"],
    ["Whistles", "https://www.whistles.com", "Clothing", "UK", "1976", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK high street (older/larger)", "No", "medium"],
    ["Reiss", "https://www.reiss.com", "Clothing", "UK", "1971", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "UK (older/larger) — included for completeness only", "No", "medium"],
    ["Sézane Beauty N/A", "https://example.invalid3", "Beauty", "France", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "PLACEHOLDER_REMOVE", "No", "low"],
    ["Colourpop skip", "https://example.invalid4", "Beauty", "US", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "PLACEHOLDER_REMOVE", "No", "low"],
    ["Lindex", "https://www.lindex.com", "Clothing", "Sweden", "1954", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Nordic women fashion retailer (older)", "No", "medium"],
    ["Kappahl", "https://www.kappahl.com", "Clothing", "Sweden", "1953", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Nordic (older/larger)", "No", "medium"],
    ["Cubus", "https://www.cubus.com", "Clothing", "Norway", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Nordic fashion chain", "No", "medium"],
    ["Bik Bok", "https://www.bikbok.com", "Clothing", "Norway", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Nordic young women fashion", "No", "medium"],
    ["Selected Femme", "https://www.selected.com", "Clothing", "Denmark", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Bestseller Group brand", "No", "medium"],
    ["Vero Moda", "https://www.veromoda.com", "Clothing", "Denmark", "1987", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Large (older) — completeness", "No", "medium"],
    ["Only", "https://www.only.com", "Clothing", "Denmark", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Bestseller Group", "No", "medium"],
    ["Pieces", "https://www.pieces.com", "Clothing", "Denmark", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Bestseller accessories/apparel", "No", "medium"],
    ["Object", "https://www.object.com", "Clothing", "Denmark", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Bestseller Group", "No", "medium"],
    ["Y.A.S", "https://www.yas.com", "Clothing", "Denmark", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Bestseller Group women", "No", "medium"],
    ["Vila", "https://www.vila.com", "Clothing", "Denmark", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Bestseller Group", "No", "medium"],
    ["JDY", "https://www.jdy.com", "Clothing", "Denmark", "Unknown", "Unknown", "Yes", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Bestseller Group", "No", "medium"],
    ["Soft Rebels", "https://softrebels.com", "Clothing", "Denmark", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown", "Danish indie mention", "Unknown", "low"],
    ["Samsøe Beauty skip", "https://example.invalid5", "Beauty", "Denmark", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "PLACEHOLDER_REMOVE", "No", "low"],
]


def main() -> None:
    out = Path(__file__).resolve().parent / "uk-eu-women-ecommerce-companies.csv"
    rows = [r for r in COMPANIES if r[0] and "PLACEHOLDER" not in "|".join(str(x) for x in r)]
    # Deduplicate by normalized name
    seen: set[str] = set()
    unique = []
    for r in rows:
        key = r[0].strip().lower()
        if key in seen:
            continue
        seen.add(key)
        unique.append(r)

    with out.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(FIELDS)
        w.writerows(unique)

    print(f"Wrote {len(unique)} companies to {out}")


if __name__ == "__main__":
    main()
